### PR TITLE
support 2.3 on CI

### PR DESCRIPTION
**Pull request by ganmacs**
ref https://github.com/socketry/protocol-http/pull/5#issuecomment-503583836

### CODE REVIEW

**Comment by ioquatix** [comment]
Hmm, looks like `unpack1` is undefined on 2.3...

The previous way is `unpack(...).first`.

**Comment by ioquatix** [comment]
I am happy to go back to `unpack(...).first` but I start asking myself is it really good idea? It's slower, Ruby 2.3 is EOL, etc. I know for some business it's important.

Maybe simpler option is to have monkey patch for backwards compatibility, e.g. if ruby is 2.3, define `unpack1`, etc. What do you think?

**Comment by ganmacs** [comment]
> Maybe simpler option is to have monkey patch for backwards compatibility, e.g. if ruby is 2.3, define unpack1, etc. What do you think?

looks good. I'll do that.

**Comment by ganmacs** [comment]
@ioquatix friendly ping

**Comment by ioquatix** [comment]
Thank you for friendly ping. I will review this weekend.

**Comment by ioquatix** [comment]
Thanks for your effort here.

**Comment by ioquatix** [comment]
@ganmacs there are more issues to sort out: https://github.com/socketry/async-http/issues/24

**Pull request merged**
